server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://user:password@peer1:8091/eureka
spring:
  application:
    name: customer
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule